<a href="https://colab.research.google.com/github/aravind-thalla/2024-stat-ml-assignments/blob/main/SML_Project_2303A52049.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('/content/sample_data/drug_consumption.csv')
df

ID      Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0        1  0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545   
1        2 -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886   
2        3  0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523   
3        4 -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615   
4        5  0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340   
...    ...      ...      ...        ...      ...        ...      ...      ...   
1880  1884 -0.95197  0.48246   -0.61113 -0.57009   -0.31685 -1.19430  1.74091   
1881  1885 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685 -0.24649  1.74091   
1882  1886 -0.07854  0.48246    0.45468 -0.57009   -0.31685  1.13281 -1.37639   
1883  1887 -0.95197  0.48246   -0.61113 -0.57009   -0.31685  0.91093 -1.92173   
1884  1888 -0.95197 -0.48246   -0.61113  0.21128   -0.31685 -0.46725  2.12700   

       Oscore   Ascore  ...  Ecstasy  Heroin  Ketamine Legalh  LSD Meth  \
0    -0.58331 -0.91699  ...      CL0     CL0       CL0    CL0  CL0  CL0   
1     1.43533  0.76096  ...      CL4     CL0       CL2    CL0  CL2  CL3   
2    -0.84732 -1.62090  ...      CL0     CL0       CL0    CL0  CL0  CL0   
3    -0.01928  0.59042  ...      CL0     CL0       CL2    CL0  CL0  CL0   
4    -0.45174 -0.30172  ...      CL1     CL0       CL0    CL1  CL0  CL0   
...       ...      ...  ...      ...     ...       ...    ...  ...  ...   
1880  1.88511  0.76096  ...      CL0     CL0       CL0    CL3  CL3  CL0   
1881  0.58331  0.76096  ...      CL2     CL0       CL0    CL3  CL5  CL4   
1882 -1.27553 -1.77200  ...      CL4     CL0       CL2    CL0  CL2  CL0   
1883  0.29338 -1.62090  ...      CL3     CL0       CL0    CL3  CL3  CL0   
1884  1.65653  1.11406  ...      CL3     CL0       CL0    CL3  CL3  CL0   

     Mushrooms Nicotine Semer  VSA  
0          CL0      CL2   CL0  CL0  
1          CL0      CL4   CL0  CL0  
2          CL1      CL0   CL0  CL0  
3          CL0      CL2   CL0  CL0  
4          CL2      CL2   CL0  CL0  
...        ...      ...   ...  ...  
1880       CL0      CL0   CL0  CL5  
1881       CL4      CL5   CL0  CL0  
1882       CL2      CL6   CL0  CL0  
1883       CL3      CL4   CL0  CL0  
1884       CL3      CL6   CL0  CL2  

[1885 rows x 32 columns]

In [3]:
feature_col_names = ['Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore','Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS']
predicted_class_names = ['Benzos']

X = df[feature_col_names].values
y = df[predicted_class_names].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Support Vector Machine  (SVM)

In [4]:
from sklearn.svm import SVC
svm = SVC(kernel="rbf", C=2,random_state=0)
svm.fit(X_train, y_train.ravel())
y_pred = svm.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.5406360424028268
              precision    recall  f1-score   support

         CL0       0.58      0.96      0.72       307
         CL1       0.00      0.00      0.00        29
         CL2       0.31      0.09      0.14        57
         CL3       0.19      0.07      0.10        76
         CL4       0.00      0.00      0.00        43
         CL5       0.00      0.00      0.00        23
         CL6       0.14      0.03      0.05        31

    accuracy                           0.54       566
   macro avg       0.17      0.16      0.14       566
weighted avg       0.38      0.54      0.42       566

[[295   1   2   9   0   0   0]
 [ 26   0   3   0   0   0   0]
 [ 43   0   5   5   0   2   2]
 [ 66   0   2   5   1   0   2]
 [ 38   0   0   3   0   1   1]
 [ 21   0   0   1   0   0   1]
 [ 22   0   4   4   0   0   1]]


# K - Nearest Neaighbour (KNN)

In [5]:
clf = KNeighborsClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.5176678445229682
              precision    recall  f1-score   support

         CL0       0.59      0.90      0.71       307
         CL1       0.08      0.03      0.05        29
         CL2       0.24      0.14      0.18        57
         CL3       0.20      0.08      0.11        76
         CL4       0.17      0.02      0.04        43
         CL5       0.00      0.00      0.00        23
         CL6       0.15      0.06      0.09        31

    accuracy                           0.52       566
   macro avg       0.20      0.18      0.17       566
weighted avg       0.40      0.52      0.43       566

[[275   7  12   7   3   1   2]
 [ 24   1   3   1   0   0   0]
 [ 40   1   8   5   1   1   1]
 [ 58   1   7   6   1   1   2]
 [ 31   0   0   5   1   2   4]
 [ 15   2   1   3   0   0   2]
 [ 23   1   2   3   0   0   2]]


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


# Logistic Regression

In [6]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.5353356890459364
              precision    recall  f1-score   support

         CL0       0.59      0.93      0.72       307
         CL1       0.12      0.07      0.09        29
         CL2       0.33      0.04      0.06        57
         CL3       0.23      0.12      0.16        76
         CL4       0.25      0.02      0.04        43
         CL5       0.00      0.00      0.00        23
         CL6       0.27      0.10      0.14        31

    accuracy                           0.54       566
   macro avg       0.26      0.18      0.17       566
weighted avg       0.43      0.54      0.44       566

[[286   8   1   9   0   1   2]
 [ 24   2   0   0   1   2   0]
 [ 41   2   2   4   1   3   4]
 [ 63   3   0   9   0   1   0]
 [ 32   0   1   7   1   0   2]
 [ 20   1   0   2   0   0   0]
 [ 16   1   2   8   1   0   3]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Perceptron Learning

In [7]:
from sklearn.linear_model import Perceptron
pr = Perceptron()
pr.fit(X_train,y_train)
y_pred = pr.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy is: 0.4558303886925795
              precision    recall  f1-score   support

         CL0       0.61      0.73      0.67       307
         CL1       0.25      0.07      0.11        29
         CL2       0.09      0.09      0.09        57
         CL3       0.23      0.18      0.20        76
         CL4       0.00      0.00      0.00        43
         CL5       0.04      0.04      0.04        23
         CL6       0.35      0.35      0.35        31

    accuracy                           0.46       566
   macro avg       0.23      0.21      0.21       566
weighted avg       0.41      0.46      0.43       566

[[225   4  29  31  10   5   3]
 [ 14   2   7   0   2   4   0]
 [ 34   1   5   6   1   4   6]
 [ 44   1   8  14   3   4   2]
 [ 24   0   3   4   0   5   7]
 [ 16   0   2   2   0   1   2]
 [  9   0   1   4   2   4  11]]
